#!/Users/donb/projects/VENV/mysql-connector-python/bin/python

# file: do_table.py

import sys
if len(sys.argv) >= 2:
    rel_name =  sys.argv[1]
else:
    print "Usage: " + "do_table" + " [relation name]"
    sys.exit(0)

import os

filename = os.path.basename(__file__)

# if logic belongs here, then presentation does not belong here.
#print ('this is generated by ' + filename)

from mako.template import Template
from mako import exceptions
from mako.lookup import TemplateLookup

mylookup = TemplateLookup(directories=['templates'], input_encoding='utf-8', output_encoding='utf-8', module_directory='/tmp/mako_modules')

mytemplate = mylookup.get_template("table.mako")

# mytemplate = Template(filename='mako/table.mako.txt', input_encoding='utf-8', output_encoding='utf-8', module_directory='/tmp/mako_modules')

import mysql.connector

cnx = mysql.connector.connect(user='root', password='',host='127.0.0.1',database='relations')

cur = cnx.cursor()

if rel_name == u"relations":
    query = "select attr1,dom1,dom2,attr2 from relations_view"
elif rel_name == u"domains":
    # query = "select dom_name, attr_name from domains_view"
    query = "select * from domains_view"
else:
    query = "SELECT * from " + rel_name

cur.execute( query )
#print cur.description

columns = [d[0].decode('utf8') for d in cur.description]
column_types = [d[1] for d in cur.description]

#rows =  [    row  for row in cur ]
#x =  [   [ t for t in r]  for r in s ]


cur_rows =  [row for row in cur]

#
#   print [type(z) for z in row]
#   [<type 'unicode'>, <type 'int'>, <type 'unicode'>, <type 'unicode'>, <type 'unicode'>, <type 'unicode'>]
#   sys.exit(0)
#

"""You can't slice a generator directly in python.
    You could use itertools.islice() as a helper function to do so.
    itertools.islice(generator, start, stop, step)
    Remember, slicing a generator will exhaust it partially.
    If you want to keep the entire generator intact,
    perhaps turn it into a tuple or list first: result = tuple(generator)
    """

try:

    d = { 
            'title':                "The relation " + rel_name, 
            'rel_name':             rel_name, 
            'classname':            "template library", 
            #'cur':              cur, 
            'cur_rows':              cur_rows, 
            'columns':              columns, 
            'column_types':              columns, 
            'rowcount':         12,
            'calling_filename':         filename,
            'tagline':      "Hyperfast relation and lightweight templating for the Python platform" 
            }

##    template = lookup.get_template(uri)

    print mytemplate.render(**d) 

##    print template.render()

except:

    print exceptions.html_error_template().render()

