#!/Users/donb/projects/VENV/mysql-connector-python/bin/python

# file: do_table.py

import sys
if len(sys.argv) >= 2:
    relation_name =  sys.argv[1]
else:
    print "Usage: " + "do_table" + " [relation name]"
    sys.exit(0)

import os

filename = os.path.basename(__file__)
print ('this is generated by ' + filename)

from mako.template import Template
from mako import exceptions
from mako.lookup import TemplateLookup

##mylookup = TemplateLookup(directories=['mako'], input_encoding='utf-8', output_encoding='utf-8', module_directory='/tmp/mako_modules')

mylookup = TemplateLookup(directories=['templates'], input_encoding='utf-8', output_encoding='utf-8')

mytemplate = mylookup.get_template("table.mako")

# mytemplate = Template(filename='mako/table.mako.txt', input_encoding='utf-8', output_encoding='utf-8', module_directory='/tmp/mako_modules')

import mysql.connector
cnx = mysql.connector.connect(user='root', password='',host='127.0.0.1',database='relations')


try:

    d = { 
            'title':        "The relation " + relation_name, 
            'relation_name':     relation_name, 
            'classname':        "template library", 
            'cnx':              cnx, 
            'tagline':      "Hyperfast relation and lightweight templating for the Python platform" 
            }

##    template = lookup.get_template(uri)

    print mytemplate.render(**d) 

##    print template.render()

except:

    print exceptions.html_error_template().render()

